#! /bin/sh

#########
#Monitor#
#########

xrandr --output HDMI-0 --mode 1920x1080 --rate 60

###########
#Autostart#
###########
pgrep -x sxhkd > /dev/null || sxhkd &
xsetroot -cursor_name left_ptr
#picom &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
feh --bg-fill --randomize ~/Pictures/wallpapers/* &
~/.config/polybar/launch.sh &
nm-applet --indicator &
rm ~/.local/share/recently-used.xbel &

########
#Config#
########
bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         0.5
bspc config window_gap           0

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop=^8 state=floating follow=on
bspc rule -a Brave-browser desktop=^2 focus=on
bspc rule -a Thunar desktop=^3 follow=on
bspc rule -a Audacious desktop=^4 follow=on
bspc rule -a mpv desktop=^4 focus=on follow=on
bspc rule -a discord desktop=^7 follow=on

bspc rule -a Lutris desktop=^5 follow=on
bspc rule -a rdr2.exe desktop=^6 state=fullscreen focus=on follow=on
bspc rule -a farcry6.exe desktop=^6 state=fullscreen focus=on follow=on
bspc rule -a metroexodus.exe desktop=^6 state=fullscreen focus=on follow=on
bspc rule -a anomalydx11avx.exe desktop=^6 state=fullscreen focus=on follow=on
bspc rule -a systemreshock-win64-shipping.exe desktop=^6 state=fullscreen focus=on follow=on
bspc rule -a aplaguetaleinnocence_x64.exe desktop=^6 state=fullscreen focus=on follow=on

bspc rule -a Screenkey manage=off
bspc rule -a xdman-Main state=floating
